# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build -c rapidsai -c conda-forge -c nvidia .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version = environ.get('CONDA_PY', 38) %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}

package:
  name: pylibcugraph
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=pylibcugraph-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=pylibcugraph-linux64 # [linux64]
    - SCCACHE_BUCKET
    - SCCACHE_REGION
    - SCCACHE_IDLE_TIMEOUT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  preserve_egg_dir: True

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - python x.x
    - cython>=0.29,<0.30
    - scikit-build>=0.13.1
    - libcugraph={{ version }}
    - libraft-headers {{ minor_version }}.*
    - libraft-distance {{ minor_version }}.*
    - pylibraft {{ minor_version}}.*
    - ucx-py {{ ucx_py_version }}
    - ucx-proc=*=gpu
    - cudatoolkit {{ cuda_version }}.*
    - rmm {{ minor_version }}.*
    - cudf {{ minor_version }}.*
    - setuptools
    - versioneer
  run:
    - python x.x
    - libcugraph={{ version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}

tests:                                 # [linux64]
  requirements:                        # [linux64]
    - cudatoolkit {{ cuda_version }}.* # [linux64]
  imports:                             # [linux64]
    - pylibcugraph                     # [linux64]

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: pylibcugraph library
